var practice_stimuli = [
    {
      "block_number": "practice",
      "triad": 1,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "melon",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "melongorilla.png",
      "correct_key": "A"
    },
    {
      "block_number": "practice",
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "gorilla",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": "practice",
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "gorilla",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": "practice",
      "triad": 1,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "melon",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "gorillamelon.png",
      "correct_key": "L"
    },
    {
      "block_number": "practice",
      "triad": 1,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "melon",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "melongorilla.png",
      "correct_key": "A"
    },
    {
      "block_number": "practice",
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "gorilla",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": "practice",
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "gorilla",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": "practice",
      "triad": 1,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "melon",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "gorillamelon.png",
      "correct_key": "L"
    },
]
var test_stimuli = [
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "melon",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 1,
      "image_path": "melongorilla.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "melon",
      "type": "shared",
      "relatedness": "related",
      "correct_response": 1,
      "image_path": "melongorilla.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "melon",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 1,
      "image_path": "melongorilla.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "geck",
      "target_word": "melon",
      "type": "shared",
      "relatedness": "unrelated",
      "correct_response": 1,
      "image_path": "melongorilla.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "melon",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "melongorilla.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "melon",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "melongorilla.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "gorilla",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "gorilla",
      "type": "shared",
      "relatedness": "unrelated",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "gorilla",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "geck",
      "target_word": "gorilla",
      "type": "shared",
      "relatedness": "related",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "gorilla",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "gorilla",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "melon",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 3,
      "image_path": "gorillamelon.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "melon",
      "type": "shared",
      "relatedness": "related",
      "correct_response": 3,
      "image_path": "gorillamelon.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "melon",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 3,
      "image_path": "gorillamelon.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "geck",
      "target_word": "melon",
      "type": "shared",
      "relatedness": "unrelated",
      "correct_response": 3,
      "image_path": "gorillamelon.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "melon",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "gorillamelon.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "melon",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "gorillamelon.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "gorilla",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 1,
      "image_path": "gorillamelon.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "gorilla",
      "type": "shared",
      "relatedness": "unrelated",
      "correct_response": 1,
      "image_path": "gorillamelon.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "gorilla",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 1,
      "image_path": "gorillamelon.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "geck",
      "target_word": "gorilla",
      "type": "shared",
      "relatedness": "related",
      "correct_response": 1,
      "image_path": "gorillamelon.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "gorilla",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "gorillamelon.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "gorilla",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "gorillamelon.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "melon",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 1,
      "image_path": "melongorilla.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "melon",
      "type": "shared",
      "relatedness": "related",
      "correct_response": 1,
      "image_path": "melongorilla.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "melon",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 1,
      "image_path": "melongorilla.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "geck",
      "target_word": "melon",
      "type": "shared",
      "relatedness": "unrelated",
      "correct_response": 1,
      "image_path": "melongorilla.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "melon",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "melongorilla.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "melon",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "melongorilla.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "gorilla",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "gorilla",
      "type": "shared",
      "relatedness": "unrelated",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "gorilla",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "geck",
      "target_word": "gorilla",
      "type": "shared",
      "relatedness": "related",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "gorilla",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "melon-gorilla",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "gorilla",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "melongorilla.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "melon",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 3,
      "image_path": "gorillamelon.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "melon",
      "type": "shared",
      "relatedness": "related",
      "correct_response": 3,
      "image_path": "gorillamelon.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "melon",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 3,
      "image_path": "gorillamelon.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "geck",
      "target_word": "melon",
      "type": "shared",
      "relatedness": "unrelated",
      "correct_response": 3,
      "image_path": "gorillamelon.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "melon",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "gorillamelon.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "melon",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "gorillamelon.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "gorilla",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 1,
      "image_path": "gorillamelon.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "gorilla",
      "type": "shared",
      "relatedness": "unrelated",
      "correct_response": 1,
      "image_path": "gorillamelon.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "gorilla",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 1,
      "image_path": "gorillamelon.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "geck",
      "target_word": "gorilla",
      "type": "shared",
      "relatedness": "related",
      "correct_response": 1,
      "image_path": "gorillamelon.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "gorilla",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "gorillamelon.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "gorilla-melon",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "gorilla",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "gorillamelon.png",
      "correct_key": "A"
    }
  ]