---
title: "Milestone 7_Analysis_Nellaphen"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

#install packages
```{r}
install.packages("tidyverse")
install.packages("emmeans")
install.packages("performance")
install.packages("see")
install.packages("patchwork")
install.packages("lmerTest")
```

#load packages
```{r}
library(tidyverse)
library(emmeans)
library(performance)
library(see)
library(patchwork)
library(lmerTest)
```

#Class Data imported

```{r}
nellaphen_data = read_csv("semantic-integration-nellaphen (2).csv")
```

#Inspect data
```{r}
#How many rows and columns are in your file?
nrow(nellaphen_data)

ncol(nellaphen_data)
#10402 rows and 42 columns

#How many unique “subjects” does this file have? How many trials did each subject do in this experiment?

nellaphen_data %>%
  pull(sona_id) %>% unique() %>% length()

nellaphen_data %>% group_by(sona_id) %>% count()
# 17 participants, each subject completed around 600 trials

#Which columns contain your independent variable(s) and dependent variable(s)?

# independent variable: *******
#dependent variables: rt (response time)

#How many levels do your independent variables have?
#*************

```


# Basic descriptives
```{r}


attention_trial_data = nellaphen_data %>%
  filter(typeoftrial == 'attention')

#What is the average accuracy in your experiment? What is the standard deviation of the accuracy?
subject_acc = attention_trial_data %>%
  group_by(sona_id) %>%
  summarize(mean_accuracy = mean(correct))

```

```{r}
#What does the histogram of reaction times look like in your experiment for the critical trials?

association_trial_data = nellaphen_data %>%
  filter(typeoftrial == 'association')

ggplot(data = association_trial_data)+
  geom_histogram(mapping = aes(x = as.numeric(rt)))

```


